# Generated by Django 5.1.3 on 2025-07-09 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0002_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Speise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('beschreibung', models.TextField(blank=True)),
                ('preis', models.DecimalField(decimal_places=2, max_digits=6)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speisen', to='nfc.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Tisch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.IntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tische', to='nfc.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Bestellung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('neu', 'Neu'), ('in_bearbeitung', 'In Bearbeitung'), ('fertig', 'Fertig')], default='neu', max_length=20)),
                ('speisen', models.ManyToManyField(to='nfc.speise')),
                ('tisch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bestellungen', to='nfc.tisch')),
            ],
        ),
    ]
